# <center>Neural Networks From Scratch</center>

# Objects

In [1]:
import numpy as np

X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]  # X is inputs or training dataset


class LayerDense:
    def __init__(self, nInputs, nNeurons):
        self.weights = 0.10*np.random.randn(nInputs, nNeurons)
        self.biases = np.zeros((1, nNeurons))
    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases

In [5]:
layer1 = LayerDense(4, 3)
layer2 = LayerDense(3, 2)

layer1.forward(X)
layer2.forward(layer1.output)

print(f"Input: \n {X}\n\nWeights for Layer1:\n{layer1.weights}\n\nBiases for Layer1:\n{layer1.biases}\n\nOutput of Layer 1: \n {layer1.output}")
print("______________________________________________________________")
print(f"Input: \n {layer1.output}\n\nWeights for Layer2:\n{layer2.weights}\n\nBiases for Layer2:\n{layer2.biases}\n\nOutput of Layer 2: \n {layer2.output}")


Input: 
 [[1, 2, 3, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]

Weights for Layer1:
[[ 0.08227853 -0.09808323  0.11162603]
 [ 0.0275336   0.04863479  0.01460379]
 [-0.25614348 -0.00333896 -0.03790899]
 [ 0.0159622   0.00251377  0.03718056]]

Biases for Layer1:
[[0. 0. 0.]]

Output of Layer 1: 
 [[-0.5911792  -0.00454609  0.12005803]
 [ 0.59029294  0.055374    0.40854114]
 [-0.9071203   0.26540919 -0.28285292]]
______________________________________________________________
Input: 
 [[-0.5911792  -0.00454609  0.12005803]
 [ 0.59029294  0.055374    0.40854114]
 [-0.9071203   0.26540919 -0.28285292]]

Weights for Layer2:
[[-0.02726614  0.08602117]
 [-0.01727124  0.05598922]
 [ 0.10053023  0.07565505]]

Biases for Layer2:
[[0. 0.]]

Output of Layer 2: 
 [[ 0.02826715 -0.04202546]
 [ 0.02401934  0.08478624]
 [-0.00828554 -0.08457075]]


So, at the end we got two neurons with the size of 3 because the input size is 3.